export default [
  {
    href: "https://shop.nextmeats.jp/products/burger",
    date: '12月17日',
    category: 'お知らせ',
    title: 'おいしくて体にも環境にも優しい、“ギルトフリー” なプラントベースバーガー「ネクストバーガー2.0」予約販売スタート',
  },
  {
    href: "https://tabi-labo.com/298211/matome-fake-meat",
    date: '12月15日',
    category: 'メディア情報',
    title: 'TABI LABOの『加速する「代替肉」市場。2021年はどうなる？』という記事で弊社が紹介されました',
  },
  {
    href: "https://bg-mania.jp/2020/12/15370734.html",
    date: '12月15日',
    category: 'メディア情報',
    title: '[東京バーゲンマニア]これからはヘルシー焼肉の時代。焼肉ライク全店舗で「フェイクミート」の提供始まったよ～！',
  },
  {
    href: "https://times.abema.tv/news-article/8637998",
    date: '12月15日',
    category: 'メディア情報',
    title: 'ABEMA TVのABEMA NEWS「ABEMAヒルズ」にて焼肉ライクとのコラボが紹介されました',
  },
  {
    href: "https://news.tbs.co.jp/newseye/tbs_newseye4150907.html",
    date: '12月14日',
    category: 'メディア情報',
    title: 'TBSテレビ「Nスタ」で焼肉ライクとのコラボが紹介されました',
  },
  {
    href: "https://www.ssnp.co.jp/news/soy/2020/12/2020-1214-1018-14.html",
    date: '12月14日',
    category: 'メディア情報',
    title: '[食品産業新聞社ニュースWEB]ネクストミーツ 新潟で代替肉工場稼働、「良質な水源」にこだわり、月間100t以上の生産量を確保',
  },
  {
    href: "https://prtimes.jp/main/html/rd/p/000000006.000062184.html",
    date: '12月14日',
    category: 'お知らせ',
    title: '本日より焼肉用代替肉「NEXTカルビ＆NEXTハラミ」の焼肉ライク全店舗での販売がスタート',
  },
  {
    href: "https://prtimes.jp/main/html/rd/p/000000007.000062184.html",
    date: '12月08日',
    category: 'お知らせ',
    title: '新潟工場の生産ラインが稼働開始',
  },
  {
    href: "https://sogyotecho.jp/news/20201130yakiniku-like/",
    date: '11月30日',
    category: 'メディア情報',
    title: '[創業手帳]「ネクストミーツ」の代替肉が「焼肉ライク」全49店舗において12/14から販売開始',
  },
  {
    href: "https://kisspress.jp/articles/30489/",
    date: '11月30日',
    category: 'メディア情報',
    title: '[Kiss PRESS]脂質が半分以下で、タンパク質は約2倍「代替肉」はじめました',
  },
  {
    href: "https://japan.cnet.com/article/35163072/",
    date: '11月30日',
    category: 'メディア情報',
    title: '[CNET Japan]肉の食感や味わいを再現したフェイクミート--焼肉ライク、「日本初の焼肉用代替肉」を展開へ',
  },
  {
    href: "https://www.o-uccino.jp/article/posts/68462",
    date: '11月29日',
    category: 'メディア情報',
    title: '[ヨム―ノ]テレビで話題【焼肉ライク】テスト販売で好評すぎて全店デビュー！「代替肉」が想像超えな件',
  },
  {
    href: "https://jp.techcrunch.com/2020/11/27/yakiniku-like-nextmeats/",
    date: '11月27日',
    category: 'メディア情報',
    title: '[TechCruch Japan]ネクストミーツの「フェイクミート」が焼肉チェーン49店舗で日本初の焼肉用代替肉として販売開始',
  },
  {
    href: "https://www.narinari.com/Nd/20201162645.html",
    date: '11月26日',
    category: 'メディア情報',
    title: '[ナリナリドットコム]日本初「焼肉屋さんで代替肉」好評で販売拡大',
  },
  {
    href: "https://www.yakiniku-like.com/2020/11/27/fake_zenten/",
    date: '11月26日',
    category: 'おしらせ',
    title: '大好評につき、焼肉ライク全店舗での焼肉用代替肉「NEXTカルビ＆NEXTハラミ」の販売が決定！12月14日(月)スタート！',
  },
  {
    href: "https://www.tbs.co.jp/guttoluck-tbs/sdgs/20201126.html#archive_box",
    date: '11月26日',
    category: 'メディア情報',
    title: 'TBSテレビ「グッとラック！」でSDGs特集の中で弊社が紹介されます',
  },
  {
    href: "https://shop.nextmeats.jp/products/gyudon",
    date: '11月16日',
    category: 'メディア情報',
    title: '小学館「DIME(ダイム)」2021年1月号で弊社のネクスト牛丼が紹介されました',
  },
  {
    href: "https://tabi-labo.com/297935/wt-3d-fakemeat",
    date: '11月13日',
    category: 'メディア情報',
    title: '[TABI LABO]未来の新定番？「3Dプリンタ」による「代替肉」の量産試作がスタート',
  },
  {
    href: "https://www.excite.co.jp/news/article/TokyoSports_2397537/?es=true&p=2",
    date: '11月13日',
    category: 'メディア情報',
    title: '東京スポーツで焼肉ライクとのコラボが取り上げられました',
  },
  {
    href: "https://www.axismag.jp/posts/2020/11/300899.html",
    date: '11月06日',
    category: 'メディア情報',
    title: '[AXIS Web Magazine]フェイクミートを開発する「ネクストミーツ」　3Dプリンタで代替肉を出力する実験を開始',
  },
  {
    href: "https://akasaka.keizai.biz/headline/3384/",
    date: '11月06日',
    category: 'メディア情報',
    title: '赤坂経済新聞で焼肉ライクとのコラボが取り上げられました',
  },
  {
    href: "https://shop.nextmeats.jp/",
    date: '11月03日',
    category: 'メディア情報',
    title: 'TBSテレビ「あさチャン！」で焼肉ライクとのコラボが取り上げられました',
  },
  {
    href: "https://prtimes.jp/main/html/rd/p/000000005.000062184.html",
    date: '11月02日',
    category: 'プレスリリース',
    title: '代替肉を3Dプリンターで出力する実験を開始',
  },
  {
    href: "https://www.pen-online.jp/magazine/pen/507-sustainable/",
    date: '11月02日',
    category: 'メディア情報',
    title: '雑誌「pen」11月15日号（11月2日発売）で弊社の商品が紹介されました',
  },
  {
    href: "",
    date: '11月01日',
    category: 'メディア情報',
    title: 'TOKYO FM「50 Artists」に弊社代表の佐々木が出演しました',
  },
  {
    href: "https://nextmeats.jp/2020/10/23/yakiniku-like/",
    date: '11月01日',
    category: 'お知らせ',
    title: '焼肉ライク直営5店舗（新橋本店、新宿西口店、上野店、赤坂見附店、渋谷店）でNEXTカルビ・NEXTハラミの販売を開始いたします',
  },
  {
    href: "https://www.ssnp.co.jp/news/soy/2020/10/2020-1028-1414-16.html",
    date: '10月28日',
    category: 'メディア情報',
    title: '[食品産業新聞]焼肉ライクに代替肉「NEXTカルビ&NEXTハラミ」、渋谷宇田川町店で無料提供、販売は5店舗限定で/ネクストミーツ',
  },
  {
    href: "https://www.fnn.jp/articles/-/100829",
    date: '10月28日',
    category: 'メディア情報',
    title: 'フジテレビ「Live News イット！」にて紹介されます',
  },
  {
    href: "https://rocketnews24.com/2020/10/27/1423807/",
    date: '10月27日',
    category: 'メディア情報',
    title: '[ロケットニュース24]代替肉の焼肉はアリなのか？ 偽物の肉オンリーでソロ焼肉をキメてみた / 味、満足感、コスパ面を本物の肉と比較',
  },
  {
    href: "https://nextmeats.jp/2020/10/23/yakiniku-like/",
    date: '10月26日',
    category: 'メディア情報',
    title: '外食日報にて焼肉ライクとのコラボが取り上げられました',
  },
  {
    href: "https://shop.nextmeats.jp/",
    date: '10月26日',
    category: 'メディア情報',
    title: 'RKB毎日放送「タダイマ！」（福岡・北部九州ローカル）で弊社の商品が取り上げられました',
  },
  {
    href: "https://netatopi.jp/article/1284832.htmlfbclid=IwAR09aTVNvspZDLKVsPh3vh077q7H_10CbGtgv7ENMayQJnN2G_ZJ3fFf6c0",
    date: '10月23日',
    category: 'メディア情報',
    title: '[ネタとぴ]焼肉セット注文で、試食を無償提供! 一人焼肉「焼肉ライク」が日本初の焼肉フェイクミートを本日23日(金)から渋谷宇田川町店で先行販売～脂質は半分以下、タンパク質は約2倍',
  },
  {
    href: "https://nextmeats.jp/2020/10/23/yakiniku-like/",
    date: '10月23日',
    category: 'プレスリリース',
    title: '焼肉ライクとのコラボ企画が本日スタート',
  },
        
  {
    href: "http://www4.fmyokohama.co.jp/future/",
    date: '10月10日',
    category: 'メディア情報',
    title: 'Fm yokohama「Futurescape」に弊社代表の佐々木が出演しました',
  },
        
  {
    href: "https://www.j-wave.co.jp/original/innovationworld/dreampitch/index.html",
    date: '10月09日',
    category: 'メディア情報',
    title: 'ラジオ番組 J-WAVE「INNOVATION WORLD」に弊社代表の佐々木が出演しました',
  },
        
  {
    href: "https://shop.nextmeats.jp/",
    date: '10月07日',
    category: 'メディア情報',
    title: '北海道テレビ「イチオシ!!」で弊社の商品が取り上げられました',
  },
        
  {
    href: "http://www.at-s.com/sbsradio/program/ippo/",
    date: '10月05日',
    category: 'メディア情報',
    title: 'SBSラジオ「牧野克彦のIPPO」に弊社代表の佐々木が出演しました',
  },
        
  {
    href: "https://www.moneypost.jp/709723",
    date: '09月30日',
    category: 'メディア情報',
    title: '[マネーポストWEB]この「牛丼」、実は牛肉を使ってない！　進化するフェイクミートの現在',
  },
        
  {
    href: "https://shop.nextmeats.jp/products/gyudon",
    date: '09月28日',
    category: '新作情報',
    title: '「ネクスト牛丼1.2」12時〜販売開始 300名限定で販売（公式サイトのみで販売）',
  },
  {
    href: "https://www.syokuraku-web.com/news/56306/",
    date: '09月17日',
    category: 'メディア情報',
    title: '[食楽web]テレビでも話題沸騰！ フェイクミートを使った「牛丼」が数量限定で販売決定！',
  },
  {
    href: "https://news.careerconnection.jp/?p=100597",
    date: '09月08日',
    category: 'メディア情報',
    title: '[キャリコネニュース]代替肉のレトルト牛丼発売へ　食感や味わいは”言われなければわからないほどの完成度”',
  },
  {
    href: "https://www.ssnp.co.jp/news/soy/2020/09/2020-0907-1020-14.html",
    date: '09月07日',
    category: 'メディア情報',
    title: '[食品産業新聞社ニュースWEB]代替肉の“レトルト牛丼”「ネクスト牛丼1.2」発売、動物性食材不使用、主原料は大豆/ネクストミーツ',
  },
  {
    href: "https://newswitch.jp/p/23660",
    date: '09月06日',
    category: 'メディア情報',
    title: '[ニュースイッチ]お肉そっくり！世界初の代替肉のレトルト牛丼、限定販売へ',
  },
  {
    href: "https://gacchiri.tv/n/n2ec79001ac51",
    date: '09月06日',
    category: 'メディア情報',
    title: 'TBSテレビ「がっちりマンデー!!」に弊社代表の佐々木が出演しました',
  },
  {
    href: "https://japanese.engadget.com/fake-meat-030054246.html",
    date: '09月04日',
    category: 'メディア情報',
    title: '[Engadget日本版]夜食でも罪悪感なし。代替肉を利用した「ネクスト牛丼1.2」9月28日発売',
  },
  {
    href: "https://jp.techcrunch.com/2020/09/04/nextmeats-gyudon/?guccounter=1guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAJ_04M5uHT3e7fzgsINpjtgTMZUgi4UWuQSYJsLmAU8NeZNKhgqzGaI_yuKYtCvDwl_SzvAG9cG5UIU2OFOI5MQCVSpQ-40SSHuFVhgyIIwhhm8n8lzGT1Yp5N43H7qcuJ0xyaZisGkDziQK71V-bdan2AVpKegSFx1fMxsOEOz_",
    date: '09月04日',
    category: 'メディア情報',
    title: '[TechCrunch Japan]フェイクミート開発のネクストミーツが代替肉によるレトルト牛丼を9月28日発売',
  },
  {
    href: "https://shop.nextmeats.jp/products/gyudon",
    date: '09月04日',
    category: 'プレスリリース',
    title: '【9月28日発売】世界初の代替肉のレトルト牛丼『ネクスト牛丼1.2』',
  },
  {
    href: "https://www.ssnp.co.jp/news/soy/2020/08/2020-0826-1005-14.html",
    date: '08月27日',
    category: 'メディア情報',
    title: '[食品産業新聞社ニュースWEB]〈大豆ミートビジネス最前線〉「代替肉で地球を救え」、ハンバーガー・焼肉など有識者や大学と連携して商品開発/ネクストミーツ',
  },
  {
    href: "https://nextmeats.co.jp/yakiniku.html",
    date: '08月26日',
    category: 'メディア情報',
    title: 'フジテレビ「めざましテレビ」で当社のネクスト焼肉が紹介されました',
  },
  {
    href: "https://rocketnews24.com/2020/08/22/1403911/",
    date: '08月22日',
    category: 'メディア情報',
    title: '[ロケットニュース24]【ここまできた】フェイクミートの世界に「焼き肉カルビ＆ハラミ」が登場！ 大豆はいつか肉を超えられるのか!?',
  },
  {
    href: "https://news.careerconnection.jp/?p=99108",
    date: '08月12日',
    category: 'メディア情報',
    title: '[キャリコネニュース]時代は植物肉!? 焼肉の代替肉「ネクスト焼肉シリーズ」発売　「ハラミ」と「カルビ」の味わいと食感が楽しめる',
  },
  {
    href: "https://japanese.engadget.com/yahoo-073010086.html",
    date: '08月05日',
    category: 'メディア情報',
    title: '[Engadget日本版]焼肉風偽肉「ネクスト焼肉シリーズ」Yahoo!ショッピングで購入可能',
  },
  {
    href: "https://nextmeats.co.jp/yakiniku.htmll",
    date: '08月05日',
    category: 'プレスリリース',
    title: '自社開発：世界初の焼肉用フェイクミート「ネクスト焼肉シリーズ」をリリース',
  },
  {
    href: "https://www.axismag.jp/posts/2020/07/255663.html",
    date: '07月31日',
    category: 'メディア情報',
    title: '[AXIS Web Magazine]日本発の「おいしい植物性の肉」ハンバーガー「ネクストバーガー1.2」が登場',
  },
  {
    href: "https://nextmeats.co.jp/burger.html",
    date: '07月28日',
    category: 'プレスリリース',
    title: '【代替肉で地球を救え】日本発のフェイクミートハンバーガー『ネクストバーガー1.2』をリリース',
  },
]
